server:
  port: 8080  # Porta do servidor

spring:
  datasource:
    url: jdbc:mysql://vrk7xcrab1wsx4r1.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/qzuf0po8d5vyguzr
    username: lyqm24drtp8b4pt7
    password: ntzzi53iui8vk373
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Cria ou atualiza tabelas automaticamente
    show-sql: true  # Exibe as queries SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # Formata as queries no console para melhor leitura

  # Configuração para evitar problemas com timezone do MySQL
  timezone: UTC
  sql:
    init:
      mode: always  # Executa scripts SQL de inicialização se existirem

logging:
  level:
    org:
      springframework:
        web: INFO  # Define o nível de log da aplicação
      hibernate:
        SQL: DEBUG  # Loga as queries SQL geradas pelo Hibernate
